import Prism from 'prismjs';

// Language components — import order matters (dependencies must load first):
// markup → css → clike → javascript → typescript → jsx → tsx, then the rest.
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-css';
import 'prismjs/components/prism-clike';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';
import 'prismjs/components/prism-jsx';
import 'prismjs/components/prism-tsx';
import 'prismjs/components/prism-json';
import 'prismjs/components/prism-json5';
import 'prismjs/components/prism-bash';
import 'prismjs/components/prism-markdown';
import 'prismjs/components/prism-yaml';
import 'prismjs/components/prism-python';
import 'prismjs/components/prism-c';
import 'prismjs/components/prism-cpp';
import 'prismjs/components/prism-java';
import 'prismjs/components/prism-sql';
import 'prismjs/components/prism-regex';
import 'prismjs/components/prism-toml';

/** Map a file extension (without dot) to a Prism language id. */
const EXTENSION_MAP: Record<string, string> = {
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'jsx',
  ts: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  tsx: 'tsx',
  html: 'markup',
  htm: 'markup',
  xml: 'markup',
  svg: 'markup',
  vue: 'markup',
  svelte: 'markup',
  css: 'css',
  json: 'json',
  jsonc: 'json',
  json5: 'json5',
  md: 'markdown',
  markdown: 'markdown',
  mdx: 'markdown',
  py: 'python',
  java: 'java',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  yml: 'yaml',
  yaml: 'yaml',
  toml: 'toml',
  sql: 'sql',
};

/** Resolve a Prism language id from a file path or extension. */
export function getPrismLanguage(pathOrExtension: string): string | undefined {
  const ext = pathOrExtension.includes('.')
    ? pathOrExtension.split('.').pop()?.toLowerCase() ?? ''
    : pathOrExtension.toLowerCase();

  const lang = EXTENSION_MAP[ext] ?? ext;
  return Prism.languages[lang] ? lang : undefined;
}

/** Escape HTML special characters. */
function escapeHtml(code: string): string {
  return code
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Highlight source code and return HTML with Prism `token` spans.
 * Unknown languages are returned HTML-escaped without coloring.
 *
 * The returned HTML is generated by Prism from the given code only (Prism
 * escapes all code content), so it is safe to render via
 * `dangerouslySetInnerHTML`.
 */
export function highlightCode(code: string, language?: string): string {
  const lang = language && Prism.languages[language] ? language : undefined;

  if (!lang) {
    return escapeHtml(code);
  }

  try {
    return Prism.highlight(code, Prism.languages[lang], lang);
  } catch (error) {
    console.warn('Syntax highlighting failed:', error);
    return escapeHtml(code);
  }
}

/** Highlight code from a file path (language inferred from the extension). */
export function highlightFile(code: string, filePath: string): string {
  return highlightCode(code, getPrismLanguage(filePath));
}
